packages/serp-report/src/pages/iframe/index.html
No braking change, only changed URLs in serp-report iframe HTML to be relative.
=> Use relative paths for vite support

package-lock.json, package.json
For now, we are installing all packages, so we need to add the dependency of the package to the main `package.json`. The `dexie` was missing but it is used by the `anonymous-communication` package.
=> Add missing dexie dependency

packages/serp-report/src/content_scripts/serp-report.js
Addresses #19. Simple check that the `String` prototype functions are available before referencing them.
=> fix: account for message.data any type

.eslintignore, packages/trackers-preview/scripts/download.js, packages/trackers-preview/src/background/index.js
Avoid parsing the trackers-preview-data on each startup. Instead ship it as JavaScript code, you allow the JavaScript engine to cache its bytecode.
JSON.parse is generally faster for dynamic data, but since the trackers-preview is hard-coded, representing it as code allows caching of the parsed bytecode if JavaScript engines support it.
=> Prefer code over JSON.parse for tracker-preview data

package-lock.json, package.json, packages/trackers-preview/scripts/download.js
Fixes a build error that you can run into (node-fetch not being present).
Forces to use Node 18, which added the native fetch API.
---
This is the error:
cd packages/anonymous-communication && npm ci
may fail with node-fetch is not present
```
> @whotracksme/webextension-packages@0.4.3 trackers-preview:download
> node ./packages/trackers-preview/scripts/download.js
node:internal/errors:484
ErrorCaptureStackTrace(err);
^
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'node-fetch' imported from /home/phil/github/webextension-packages/packages/trackers-preview/scripts/download.js
at new NodeError (node:internal/errors:393:5)
```
=> Use native fetch

packages/anonymous-communication/src/errors.js, packages/anonymous-communication/src/index.js, packages/anonymous-communication/src/trusted-clock.js, packages/anonymous-communication/src/utils.js, packages/anonymous-communication/test/utils.spec.js, packages/reporting/example/index.js, packages/reporting/src/alive-check.js, packages/reporting/src/country-provider.js, packages/reporting/src/duplicate-detector.js, packages/reporting/src/patterns-updater.js, packages/reporting/src/reporting.js, packages/reporting/src/sanitizer.js, packages/reporting/src/utils.js, packages/reporting/test/alive-check.spec.js, packages/reporting/test/country-provider.spec.js, packages/reporting/test/duplicate-detector.spec.js, packages/reporting/test/index.js, packages/reporting/test/patterns-updater.spec.js, packages/reporting/test/reporting.spec.js
Changes in reporting and anonymous-communication to integrate it in the Ghostery Manifest V3 Extension:
* Move "alive" message and country detection into reporting
* Move the clock to anonymous-communication and make it part of its public interface
* Bug fixes (e.g. problems with caching in the pattern-updater)
refs https://github.com/ghostery/ghostery-extension/pull/934
=> Integrate reporting in Ghostery (Manifest V3)

packages/reporting/src/request-reporter.js
this.requestMonitor starts as undefined, which is !== null.
Fixes:
```
Error while observing options:  TypeError: this.requestMonitor is undefined
unload moz-extension://711062c7-0b3e-4e88-aa29-a86c29e705aa/node_modules/@whotracksme/webextension-packages/packages/reporting/src/request-reporter.js:66
setup moz-extension://711062c7-0b3e-4e88-aa29-a86c29e705aa/background/reporting/index.js:152
wrapper moz-extension://711062c7-0b3e-4e88-aa29-a86c29e705aa/store/options.js:281
observe moz-extension://711062c7-0b3e-4e88-aa29-a86c29e705aa/store/options.js:293
[options.js:295:13](moz-extension://711062c7-0b3e-4e88-aa29-a86c29e705aa/store/options.js)
observe moz-extension://711062c7-0b3e-4e88-aa29-a86c29e705aa/store/options.js:295
```
=> fixed: unload should not throw if it called before the object is initialized

packages/reporting/src/webrequest-pipeline/utils/webrequest.js
Currently, there are many info warnings that are repetitive:
```
WTM [webrequest-pipeline]   log: webRequest.onCompleted called without listener being assigned webrequest.js line 295 > importedModule:80:14
WTM [webrequest-pipeline]   log: webRequest.onHeadersReceived called without listener being assigned 2 webrequest.js line 295 > importedModule:80:14
WTM [webrequest-pipeline]   log: webRequest.onCompleted called without listener being assigned 2 webrequest.js line 295 > importedModule:80:14
WTM [webrequest-pipeline]   log: webRequest.onHeadersReceived called without listener being assigned webrequest.js line 295 > importedModule:80:14
WTM [webrequest-pipeline]   log: webRequest.onCompleted called without listener being assigned webrequest.js line 295 > importedModule:80:14
WTM …
```
=> Only warn once about missing listeners

packages/reporting/src/request/steps/cookie-context.js, packages/reporting/src/request/steps/oauth-detector.js, packages/reporting/src/request/steps/token-checker/token-domain.js, packages/reporting/src/request/steps/token-examiner.js, packages/reporting/src/request/steps/token-telemetry/cached-entry-pipeline.js, packages/reporting/src/webrequest-pipeline/cname-uncloak.js
With this change, it should be more intuitive to understand which component owns the keys.
=> Naming consistency (request-reporter != url-reporter)

packages/reporting/src/http.js
Detect more types of opaque requests in doublefetch and treat them as permanent errors
=> Fixed: detect more types of opaque requests in doublefetch

packages/reporting/src/pages.js
If you add APIs to the list that do not support "responseHeaders", Chrome will ignore them, but Firefox will fail.
This is intended to keep the assumptions on the APIs as low as possible. Currently, all APIs that are used support "responseHeaders", so the change is not fixing a problem in production.
=> Limit assumption about browser APIs

packages/reporting/src/page-quorum-check-handler.js
Due to a typo, the redirects were not included. Also, renamed the field to be more descriptive.
=> Fixed missing redirects

packages/reporting/src/doublefetch-page-handler.js, packages/reporting/test/doublefetch-page-handler.spec.js, packages/reporting/test/sanitizer.spec.js
Avoid floating points in the final message. Also, apply noise to defend against unintentionally leaking details on the clock.
=> Improve sanitizers

package-lock.json, package.json, packages/reporting/src/html-parser.js, packages/reporting/src/page-structure.js, packages/reporting/test/helpers/dom-parsers.js
* Removes unused code in the page structure analyzer
* Enables caching in linkedom, which is slightly faster
Note on Linkedom caching: caching increases the memory footprint, but I do not expect it to be a problem. It is not easy to measure, but the runtime was about 1/3 faster in tests. Our use cases should benefit from caching, since there are never DOM manipulation after the HTML is parsed.
=> Performance tweaks and cleanups

packages/reporting/src/doublefetch-page-handler.js
Currently, it is also dropped but only after showing a warning:
https://github.com/whotracksme/webextension-packages/blob/c059da7db379ca94bef99bab9093e9b7dfce1161/packages/reporting/src/doublefetch-page-handler.js#L50
=> Fixed: empty strings should also be treated as missing titles

package-lock.json, package.json
Update to latest linkedom, which fixes a regression after enabling caching
refs https://github.com/WebReflection/linkedom/pull/266
refs https://github.com/ghostery/ghostery-extension/pull/1511
=> Update to latest linkedom (fixes empty document.title)

packages/reporting/src/utils.js, packages/reporting/test/utils.spec.js
Fixes a test that can rarely fail. For specific inputs "equalityCanBeProven" would have failed with an exception:
```
FAILED TESTS:
#equalityCanBeProven
✖ proving equality implies deepEqual
Chrome Headless 123.0.6312.105 (Linux x86_64)
Property failed after 38 tests
{ seed: -1867831413, path: "37:0:4:2:2:3:4:3:5:5:81:81", endOnFailure: true }
Counterexample: [{},{"":{}," ":[{"toString":undefined}]}]
Shrunk 11 time(s)
Got error: TypeError: Cannot convert object to primitive value
Stack trace: TypeError: Cannot convert object to primitive value
at Array.join (<anonymous>)
at Array.toString (<anonymous>)
at Array.join (<anonymous>)
at Array.toString (<anonymous>)
at Array.sort (<anonymous>)
at equalityCanBeProven (src/utils.js:233:71 <- test/index.js:48499:72)
at test/utils.spec.js:129:13 <- …
```
=> Fixed: do not depend on Array.toString for sorting Object.entries

packages/reporting/package.json
reporting still had a local overwrite of linkedom with an old version. This created problems when using npm link
=> Upgrade linkedom in all places

packages/reporting/src/doublefetch-page-handler.js, packages/reporting/src/url-cleaner.js, packages/reporting/test/url-cleaner.spec.js
Since the URL hash gets removed in a previous normalization step, we can ignore it when comparing URLs. But only if there are strong indicators that we are not dealing with a single page application.
=> Improve the heuristic that compares URLs before and after double-fetch

packages/reporting/src/request/page-telemetry.js
`page.created` is not initialized from `Date.now()`, but contains a higher resolution. In the old messages, it was an integer value, now it is a float. Arguably, we should apply some noise to it; but for now, round at least to guarantee integer values.
=> Do not use sub-millisecond resolution for times

reporting/src/duplicate-detector.js, reporting/test/duplicate-detector.spec.js
The ".[]" expansion in deduplicator expressions should also work on plain objects, not just arrays.
=> Support expansion for plain objects in deduplicator expressions

reporting/src/pages.js, reporting/test/pages.spec.js
Fixes a problem where the in-memory session could not be restored:
Error: "Failed to restore previous state from in-memory session (if there was any) TypeError: val is undefined"
The reason was that cancelled lazy-vars where not properly handled during the serialization step. Also, the deserialization was not prepared to handle nil values.
=> Fix in-memory session serialization

reporting/src/patterns.js, reporting/test/patterns.spec.js
When parsing JSON, we should no attempt to extract implicitly properties like 'toString'. This guarantees that the function will always return a result of type 'string'.
This should also fix rare test failures in the QuickCheck tests.
=> Improve 'json' primitive

reporting/src/request/index.js, reporting/src/request/steps/page-logger.js, reporting/src/request/utils/chrome-storage-map.js, reporting/src/webrequest-pipeline/page-store.js, reporting/src/webrequest-pipeline/page.js, reporting/src/webrequest-pipeline/webrequest-context.js, reporting/test/webrequest-pipeline/page-store.test.js
`chrome.storage` is incapable to persisting instances of JavaScipt Classes, so Page objects could not be retrieved from it. This PR changes Page representation to plain object.
=> PageStore fixes

.github/workflows/release.yml
The new tests assume Node 22. Also, upgrade to Ubuntu 24.04.
=> Fix breakage in tests: node 22 is now required

reporting/src/sanitizer.js, reporting/test/sanitizer.spec.js
Filter out uncommon URLs where the hostname is a IPv4 address.
=> Stricter URL filtering

reporting/karma.conf.cjs, reporting/src/pages.js, reporting/test/pages.spec.js
If a link opens in a new tab, some information could get lost.
Also, improved the output of the tests. Not enabled by default, but only when the VERBOSE_REPLAY environment is set.
Additionally, ENABLE_SELF_CHECKS runs self check at each step. It is also an opt-in, because it comes with a performance cost and also may change the results.
=> Preserve "openedFrom" information during redirects opening in new tabs

reporting/src/request/steps/token-telemetry/index.js, reporting/src/request/steps/token-telemetry/key-pipeline.js
Keys telemetry could accumulate too many tokens that cannot be pushed via the anonymous communication due to its size restrictions. Such case was noticed at soundcloud.com, see for details of such message https://github.com/ghostery/broken-page-reports/issues/873#issuecomment-2450496021
With the sample of tokens being sent, there is an expectation for the `QSWhitelist` to catch up and fix the soundcloud.com breakage.
=> Request: keys pipeline picks a random tokens if too many

reporting/src/request/index.js
Compatibility checks should also have an effect on placeholder replacements in onBeforeRequest, and not be limited to onBeforeSendHeaders; otherwise, exceptions in https://cdn.ghostery.com/antitracking/config.json are ignored.
From my understanding, the compatibility lists so far have only an effect on HTTP headers, but not on HTTP url parameters.
(Note: placeholder replacement means replacing a potential tracking parameter by the fixed string "ghostery").
=> Run compatibility checks before placeholder replacements in onBeforeRequest

reporting/src/request/index.js
- fixed: recordClick: this.cookieContext only available if ready
- logging if events or requests get dropped if not ready
=> Fixed errors when request reporter is not ready yet

reporting/src/request/page-store.js
Handle the lack of chrome.windows gracefully. Currently, anti-tracking crashes on startup on Android.
=> Fix anti-tracking on Android

reporting/example/index.js, reporting/src/communication-proxy/attrack-message-handler.js, reporting/src/job-scheduler.js, reporting/src/reporting.js, reporting/src/request/index.js, reporting/test/request/index.spec.js, reporting/test/request/index.test.js
Provide a function to send anti-tracking messages through the job scheduler.
It is intended to smooth out the traffic during peaks like the begin of a new day, where all clients generate keysv2/tokensv2 messages. Also, having randomized client-side delays for tp_events introduces the possibility of message reordering, which is intended.
=> Randomly delay sending of request reporter messages 

reporting/src/request/index.js
In the actual (background page restart) unload scenario there is no way to perform async operation so touching storage wont work.
In the soft unload scenario, config should clean its timers.
=> Request: fix unload

package-lock.json, package.json, reporting/example/index.js, reporting/snapshots/0001/snapshot.json, reporting/snapshots/0002/snapshot.json, reporting/snapshots/0003/snapshot.json, reporting/snapshots/0004/snapshot.json, reporting/snapshots/0005/snapshot.json, reporting/snapshots/0006/snapshot.json, reporting/src/alive-message-generator.js, reporting/src/reporting.js, reporting/src/request/index.js, reporting/test/alive-message-generator.spec.js, reporting/test/reporting.spec.js, reporting/test/request/index.spec.js, reporting/test/request/index.test.js
Remove "browserInfoProvider":
* Handle browser detection for alive-messages as an implementation detail of the urlReporter. Also, include platform (e.g. "desktop") and engine (e.g. "Blink") in the message.
* Removed also from the requestReporter. For backward, the values are mapped to the original values. With the difference that Safari is additionally detected, but the Ghostery browser is removed.
=> Remove browserInfoProvider dependency

communication/src/proxied-http.js, reporting/src/job-scheduler.js, reporting/test/helpers/in-memory-job-scheduler.js, reporting/test/job-scheduler.spec.js
Retry mechanism for recoverable jobs
* Jobs are placed in a "retryable" queue. If a job of the same type
succeeds, one job from that queue will be put into the "ready" queue.
* By default, jobs will be dropped after they failed three times. Jobs that
failed with an unclassified or permanent error will never be retried.
=> Error recovery

reporting/src/communication-proxy/attrack-message-handler.js
Since sending via the jobScheduler is reliable now, we can introduce higher latencies for the anti-tracking messages. Also, higher cooldowns.
The idea is mostly to smooth out the traffic that we receive on the server. Anti-tracking notoriously spikes during 0:00 UTC, and these changes are intended to decrease the maximum amplitude.
=> Mitigate midnight spike of anti-tracking signals
