packages/serp-report/src/background/serp-report.js
packages/serp-report/src/content_scripts/serp-report.js
packages/serp-report/src/pages/iframe/wtm-report.js
packages/ui/src/components/wtm-stats.js

Add option to disable trackers preview from the iframe directly

---

.github/workflows/release.yml
package-lock.json
package.json

setup copied from ghostery/common

Release automation

---

packages/serp-report/src/content_scripts/serp-report.css
packages/serp-report/src/content_scripts/serp-report.js

Generally, I moved the wheel just after the URL, as sometimes there are additional features after, which can break the UI. Also, It fixes #9. After working with the result page for a few hours constantly, I think users might want to turn off the feature as it is too destructive. When I made a wheel slightly smaller and moved to the URL, now it looks more like a native google feature, rather than something strange. 
* Clean up of the UI code in content script
* Resized wheel to 16px - the 22px wheel was in my opinion too big, and hard to put in the line with the text (as we have limited options for styling it)
* One general styling without absolute positioning (JS calculated stuff)
* The script only checks the DOM where to put the wheel
* Fixed bug, when popup displays out of the screen …

Add support for mobile Firefox old layout for google

---

packages/serp-report/src/content_scripts/serp-report.js

Close popup when user clicks on a link

---

packages/trackers-preview/src/content_scripts/styles.css
packages/trackers-preview/src/page_scripts/index.js

* Fixes auto-resize of the iframe window
* Minor CSS fixes for the iframe container

Fix trackers-preview iframe UI

---

packages/trackers-preview/src/background/index.js

Trackers Preview: fix import of pre-generated data

---

packages/anonymous-communication/src/proxied-http.js

Clarify the purpose of the ProxiedHttp class. Also, explain what is currently working with Manifest V3 and what functionality is intended to port.

Update comments in ProxiedHttp

---

packages/reporting/test/search-extractor.spec.js

"." should not match any char and an arbitray number of wildcards should be supported

Improve the test suite runner

---

packages/reporting/src/job-scheduler.js
packages/reporting/src/url-analyzer.js
packages/reporting/test/patterns.spec.js
packages/reporting/test/url-analyzer.spec.js

Extend the set of search pages that WhoTracks.me reporting supports.

Support more search pages

---

packages/reporting/src/patterns.js
packages/reporting/test/patterns.spec.js

Primitive to handle JSON encoded data.

Added "json" primitive to handle JSON data

---

packages/reporting/src/request/index.js
packages/reporting/src/request/steps/token-telemetry/index.js

We need separate messages, since the sending protocol differs between MV2 and MV3 ("hpn" vs "hpn-lite").

Introduce new messages for MV3 anti-tracking

---

packages/reporting/example/index.js
packages/reporting/example/inspector/index.html
packages/reporting/example/inspector/index.js
packages/reporting/example/manifests/chromium.json
packages/reporting/example/manifests/firefox.json
packages/reporting/example/tests/test1.html
packages/reporting/src/request/page-telemetry.js
packages/reporting/src/webrequest-pipeline/page-store.js
packages/reporting/src/webrequest-pipeline/page.js

refs https://github.com/whotracksme/whotracks.me/issues/333

Fix stats leakage

---

packages/reporting/src/request/index.js

Fixes a typo that breaks the compatibility list check.

Fix compatibility list check

---

packages/reporting/src/index.js
packages/reporting/src/job-scheduler.js
packages/reporting/src/logger.js
packages/reporting/src/page-structure.js
packages/reporting/src/reporting.js

Improve the error messages and make the logger more configurable

Improve logging

---

packages/reporting/example/index.js
packages/reporting/src/alive-check.js
packages/reporting/src/alive-message-generator.js
packages/reporting/src/country-provider.js
packages/reporting/src/persisted-bitarray.js
packages/reporting/src/quorum-checker.js
packages/reporting/src/reporting.js
packages/reporting/test/alive-check.spec.js
packages/reporting/test/alive-message-generator.spec.js
packages/reporting/test/index.js
packages/reporting/test/reporting.spec.js

Includes more information about the browser, but shares only if the configuration is popular enough (meaning there are enough users sharing the same configuration).

Improved alive messages

---

package-lock.json
package.json

Fixes `Error: fatal: ' 9007199254740991': not an integer`

Fixed a regression with "auto"

---

packages/reporting/src/errors.js
packages/reporting/src/patterns.js
packages/reporting/src/sanitizer.js
packages/reporting/src/search-extractor.js
packages/reporting/src/url-analyzer.js
packages/reporting/src/url-cleaner.js
packages/reporting/test/helpers/dom-parsers.js
packages/reporting/test/index.js
packages/reporting/test/patterns.spec.js
packages/reporting/test/sanitizer.spec.js
packages/reporting/test/search-extractor.spec.js
packages/reporting/test/url-analyzer.spec.js
packages/reporting/test/url-cleaner.spec.js

Includes new builtins (removeParams, relaxedMaskU, requireURL).

Improvements to patterns and URL dections

---

packages/reporting/src/patterns.js
packages/reporting/src/reporting.js
packages/reporting/src/search-extractor.js
packages/reporting/src/utils.js
packages/reporting/test/patterns-updater.spec.js
packages/reporting/test/search-extractor.spec.js

* Adds support for optional pruning (in the new "preprocessing" section)
* Adds an optional minimum version (in the new "_meta" section)

DSL: added optional pruning & minVersion

---

packages/reporting/src/doublefetch-page-handler.js
packages/reporting/src/page-structure.js
packages/reporting/test/doublefetch-page-handler.spec.js
packages/reporting/test/sanitizer.spec.js

Improve the heuristics for double-fetch on pages where the canonical URL gets outdated after history navigations.

Better handling of single-page applications in double-fetch

---

packages/reporting/src/doublefetch-page-handler.js
packages/reporting/test/doublefetch-page-handler.spec.js
packages/reporting/test/sanitizer.spec.js

Better handling of situation where encoding gets broken after doublefetch

Improved title matching

---

reporting/src/patterns.js
reporting/test/patterns.spec.js

To be used with a fixed set of allowed values. Forces that all unknown values will be dropped.

New builtin: filterExact

---

reporting/src/url-analyzer.js
reporting/test/url-analyzer.spec.js

Improve the detection of Google URLs

Extend the list of public search engines

---

reporting/src/patterns.js
reporting/test/patterns.spec.js

New builtin: "trim"

---

reporting/src/alive-message-generator.js
reporting/test/alive-message-generator.spec.js

Inject the "navigator" API to set the value explicitly in the test.

Test fixed: lifted the unintended dependency on the LANG environment

---

reporting/src/request/index.js
reporting/src/request/steps/redirect-tagger.js
reporting/src/webrequest-pipeline/page-store.js
reporting/src/webrequest-pipeline/webrequest-context.js

It looks like the redirect detection for the main_frame was not really in use.

Remove main_frame redirect detection

---

reporting/src/webrequest-pipeline/page-store.js

Fix: page store tab active listener

---

reporting/src/request/index.js

Preserves the information where the setTimeout(..., 1) came from, since it is unclear if it optimal to delay like that. [Note: Potentially, it should be rather setTimeout(..., 0) or just run it without any delay, but that would need some testing.]
Follow-up to https://github.com/whotracksme/webextension-packages/pull/111

Marker to keep the context around the 1ms delays

---

reporting/src/request/index.js

Anti-tracking initialization: better error handling and logging

Improved error handling of anti-tracking lazy initialization

---

reporting/src/request/index.js

This fixes the TODO about delays in the code. They most likely originated from a situation where they exists for performance reasons. However, in the context of anti-tracking, there is no need for it - it could actually even harming performance - but the async operation was adding unnecessary complexity to the control flow.

Request: process webRequest in sync

---

reporting/src/url-analyzer.js
reporting/test/url-analyzer.spec.js

Update url classifier regexp

---

reporting/example/index.js
reporting/src/request/config.js
reporting/src/request/index.js
reporting/src/request/utils/utils.js
reporting/src/request/utils/webrequest.js

Add a dry-run mode, where anti-tracking will run but skips the fingerprinting removal.

Add dry-run mode for anti-tracking

---

reporting/src/request/steps/token-telemetry/key-pipeline.js

Document why keyvs2 may fall back to sending only samples instead of full lists.
refs https://github.com/whotracksme/webextension-packages/pull/131

Document sampling

---

communication/src/errors.js
communication/src/server-public-key-accessor.js

Use a recoverable error if public keys cannot be fetched.

Better error handling if fetching public keys fails

---

reporting/src/doublefetch-page-handler.js
reporting/test/doublefetch-page-handler.spec.js

Slightly improve the title matching by allowing limited removal of chars.

Improve title matching

---

reporting/src/http.js

Port the missing anonymousHttpGet header override to Manifest V3. It uses the DNR API instead of blocking webrequestAPI.

MV3 support for anonymousHttpGet

---

reporting/src/errors.js
reporting/src/http.js
reporting/src/patterns.js
reporting/src/search-extractor.js
reporting/test/http.spec.js
reporting/test/index.js

Provides an isolated context where information can be shared between requests.

Added support for multi-step doublefetch.

---

reporting/src/request/index.js

Fix regression from https://github.com/whotracksme/webextension-packages/commit/1128009e594a01a4cabc5f9ea42621eb79308bec

Fixed: TypeError: this.config is undefined

---

.github/workflows/release.yml
.github/workflows/tests.yml

Upgrade Github actions

---

reporting/src/search-extractor.js
reporting/test/search-extractor.spec.js

Optional "omitIfExistsAny" field to filter out redundant messages.

Support for filtering out redundant signals

---

package-lock.json
reporting/.gitignore
reporting/example/index.js
reporting/example/manifests/chromium.json
reporting/package.json
reporting/rollup.config.cjs
reporting/src/errors.js
reporting/src/http.js
reporting/src/offscreen/doublefetch/index.html
reporting/src/offscreen/doublefetch/index.js
reporting/src/patterns.js
reporting/test/http.spec.js

Extend the double-fetch DSL to better support dynamic pages.

Initial support for dynamic double-fetch

---

reporting/src/http.js
reporting/src/search-extractor.js

Implement the missing header overwrite for dynamic doublefetch steps

Added missing header overwrite in doublefetch
